import{mockResult,normalizeResultData}from'./mock-data.js';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];let data=normalizeResultData(mockResult),timers=[],activeCats=new Set(['models','queries','competitors','sources']);
const positions={top:[['company',50,80,'company'],['ChatGPT',18,24,'models'],['Gemini',76,20,'models'],['Perplexity',84,55,'models'],['Queries',20,62,'queries'],['Competitors',70,70,'competitors'],['Sources',38,69,'sources']],analysis:[['company',50,50,'company'],['models',19,28,'models'],['queries',77,23,'queries'],['competitors',79,70,'competitors'],['sources',22,74,'sources']]};
function node(label,x,y,cat='company'){const n=document.createElement('span');n.className=`net-node ${cat}`;n.textContent=label==='company'?data.displayName:label;n.style.left=x+'%';n.style.top=y+'%';return n}
function line(stage,x1,y1,x2,y2,cat='',strength=.5){const l=document.createElement('i'),dx=x2-x1,dy=y2-y1;l.className=`net-line ${cat}`;l.style.cssText=`left:${x1}%;top:${y1}%;width:${Math.hypot(dx,dy)}%;transform:rotate(${Math.atan2(dy,dx)}rad);--edge-strength:${strength}`;stage.append(l)}
function renderSimple(stage,type,visible=99){stage.innerHTML='';positions[type].forEach((p,i)=>{if(i){line(stage,positions[type][0][1],positions[type][0][2],p[1],p[2],p[3])}const n=node(...p);if(type==='top'&&i===0)n.textContent='YOUR COMPANY';if(i>=visible)n.style.opacity=.08;stage.append(n)})}
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('is-active',s.dataset.screen===name));const s=$(`[data-screen="${name}"]`);s.classList.add('screen-transition');window.scrollTo(0,0)}
function setupAnalysis(){const list=$('#analysis-steps');list.innerHTML=data.analysisStages.map((s,i)=>`<li><b>${String(i+1).padStart(2,'0')} — ${s.label}</b><span>${s.value}</span></li>`).join('');renderSimple($('[data-network="analysis"]'),'analysis',1)}
function startAnalysis(input){data=normalizeResultData(mockResult,input);$('#analysis-company').textContent=input;setupAnalysis();showScreen('analyzing');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,duration=reduced?120:620;data.analysisStages.forEach((stage,i)=>{timers.push(setTimeout(()=>{const steps=$$('#analysis-steps li');steps.forEach((x,j)=>{x.classList.toggle('active',j===i);if(j<i)x.classList.add('done')});$('#progress-value').textContent=Math.round((i+1)/data.analysisStages.length*100);renderSimple($('[data-network="analysis"]'),'analysis',Math.min(5,i+1));if(i===data.analysisStages.length-1)timers.push(setTimeout(showResult,reduced?80:600))},i*duration))})}
function showResult(){timers.forEach(clearTimeout);showScreen('result');renderResult()}
function renderControls(){const labels={models:'AI MODELS',queries:'QUERIES',competitors:'COMPETITORS',sources:'SOURCES'},colors={models:'var(--cyan)',queries:'var(--acid)',competitors:'var(--orange)',sources:'var(--blue)'};activeCats=new Set(Object.keys(labels));$('#map-controls').innerHTML=Object.keys(labels).map(c=>`<button data-cat="${c}" aria-pressed="true"><i style="background:${colors[c]}"></i>${labels[c]}</button>`).join('');$$('#map-controls button').forEach(b=>b.onclick=()=>{const c=b.dataset.cat;activeCats.has(c)?activeCats.delete(c):activeCats.add(c);b.setAttribute('aria-pressed',activeCats.has(c));updateMapFilters()})}
function renderGraph(){const map=$('#result-map');map.innerHTML='';const mobile=innerWidth<700,all=data.graph.nodes,limits={models:3,queries:2,competitors:2,sources:2},seen={};const visible=mobile?all.filter(x=>(seen[x.category]=(seen[x.category]||0)+1)<=limits[x.category]):all;const groups=mobile?{models:{start:-145,end:-75,r:32},queries:{start:-35,end:15,r:35},competitors:{start:35,end:85,r:34},sources:{start:115,end:165,r:35}}:{models:{start:-155,end:-65,r:36},queries:{start:-55,end:35,r:40},competitors:{start:45,end:135,r:38},sources:{start:145,end:235,r:41}};const by={};visible.forEach(x=>(by[x.category]??=[]).push(x));Object.entries(by).forEach(([cat,items])=>items.forEach((item,i)=>{const g=groups[cat],a=(g.start+(items.length===1?45:i/(items.length-1)*(g.end-g.start)))*Math.PI/180,x=50+Math.cos(a)*g.r,y=50+Math.sin(a)*g.r;line(map,50,50,x,y,cat,item.strength);const n=node(item.short||item.label||item.name,x,y,cat);n.dataset.cat=cat;n.style.setProperty('--node-strength',item.strength);n.title=item.name;map.append(n)}));map.append(node('company',50,50,'company'));updateMapFilters()}
function updateMapFilters(){$$('#result-map [class*="net-"]').forEach(el=>{const c=['models','queries','competitors','sources'].find(x=>el.classList.contains(x));if(c)el.classList.toggle('hidden',!activeCats.has(c))})}
function renderResult(){renderControls();renderGraph();$('#model-bars').innerHTML=data.models.map(x=>`<div class="model-row"><span>${x.name}</span><i style="--value:${x.value}%"></i><b>${x.value}</b></div>`).join('');const qs=[data.queries[0],data.queries[1]];$('#query-examples').innerHTML=qs.map(x=>`<div class="query-example ${x.status}"><b>${x.status==='strong'?'STRONG':'WEAK'}</b><span>${x.name}</span></div>`).join('');$('#source-list').innerHTML=data.sources.map(x=>`<div class="source-row"><span>${x.name}<br><small>${x.label}</small></span><i style="--value:${x.count/8*100}%"></i><b>${x.count}</b></div>`).join('')}
$('#search-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#company-input'),v=input.value.trim();if(!v){$('#search-error').textContent='会社名・店舗名・URLを入力してください。';input.focus();return}$('#search-error').textContent='';startAnalysis(v)});$('#company-input').addEventListener('input',()=>$('#search-error').textContent='');$('#example-fill').onclick=()=>{$('#company-input').value='世田谷ホーム';$('#company-input').focus()};$('#skip-analysis').onclick=showResult;$('#new-search').onclick=()=>{timers.forEach(clearTimeout);showScreen('top');$('#company-input').focus()};addEventListener('resize',()=>{if($('[data-screen="result"]').classList.contains('is-active'))renderGraph()});renderSimple($('[data-network="top"]'),'top');setupAnalysis();
