import './sample-kyoudo.js';

const sales$=s=>document.querySelector(s);
let salesId=new URLSearchParams(location.search).get('diagnosis'),salesToken=salesId?localStorage.getItem(`madoha-access-${salesId}`):null;
let salesSite,salesQuestions=[],salesFreeIds=[],salesWarningCodes=[],salesTurnstileToken='',salesShown='',salesStage='';
const salesEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function salesApi(path,method='GET',body){const response=await fetch(`/api/sales/${path}`,{method,headers:{'content-type':'application/json',...(salesToken?{'x-diagnosis-token':salesToken}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'処理できませんでした。');return data;}
const salesError=e=>{sales$('#sales-error').textContent=e.message||e;};
sales$('#site-form').onsubmit=async event=>{event.preventDefault();try{const data=await salesApi('inspect','POST',{url:sales$('#site-url').value});salesSite=data.site;sales$('#site-description').textContent=`公式ページ：${salesSite.title}`;const entity=sales$('#entity-form');entity.elements.name.value ||= salesSite.title;entity.elements.main_services.value ||= (salesSite.headings||[]).slice(0,5).join('\n');entity.hidden=false;entity.elements.name.focus();}catch(e){salesError(e);}};
sales$('#entity-form').onsubmit=async event=>{event.preventDefault();try{const form=new FormData(event.target);const entity=Object.fromEntries(form);entity.main_services=entity.main_services.split('\n').map(x=>x.trim()).filter(Boolean);entity.faq=entity.faq.split('\n').map(x=>x.trim()).filter(Boolean);entity.official_url=salesSite.url;entity.headings=salesSite.headings||[];const data=await salesApi('draft','POST',{entity});salesId=data.id;salesToken=data.token;localStorage.setItem(`madoha-access-${salesId}`,salesToken);history.replaceState(null,'',`?diagnosis=${salesId}`);salesQuestions=data.questions;salesFreeIds=data.free_question_ids;sales$('#input-stage').hidden=true;sales$('#questions-stage').hidden=false;sales$('#mix-reason').textContent=data.mix.reason;salesShowQuestions();await salesTurnstile();}catch(e){salesError(e);}};
function salesShowQuestions(){sales$('#question-list').innerHTML=salesQuestions.map(q=>`<li>${salesEscape(q.question_text)}<small>${salesFreeIds.includes(q.id)?'無料で調査する質問 · ':''}${q.kind==='nonbrand'?'AIに候補として選ばれるか':'AIに自社がどう理解されているか'}</small></li>`).join('');}
async function salesTurnstile(){const c=await salesApi('config');if(!c.turnstile_site_key)throw new Error('無料診断の受付準備中です。');if(typeof window.turnstile?.render!=='function')await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.onload=resolve;s.onerror=reject;document.head.append(s);});window.turnstile.render('#cf-turnstile',{sitekey:c.turnstile_site_key,action:'free_diagnosis',appearance:'interaction-only',callback:token=>{salesTurnstileToken=token;sales$('#start-free').disabled=false;},'expired-callback':()=>{salesTurnstileToken='';sales$('#start-free').disabled=true;}});}
sales$('#start-free').onclick=async()=>{sales$('#start-free').disabled=true;try{await salesApi(`${salesId}/start`,'POST',{turnstile_token:salesTurnstileToken});sales$('#questions-stage').hidden=true;await salesPoll();}catch(e){salesError(e);if(typeof window.turnstile?.reset==='function')window.turnstile.reset();}};
function salesRenderReport(report){globalThis.MADOHA_RENDER_REPORT(report);const n=report.queries.length,d=report.queries.filter(q=>q.kind==='nonbrand').length,b=n-d;const counts=sales$('#report').querySelectorAll('.hero dd');counts[0].textContent=`${n}問`;counts[2].textContent=`${n*3}件`;const intros=sales$('#report').querySelectorAll('.report-intro');if(intros[0])intros[0].querySelector('p').textContent=`${d} QUESTIONS / ${d*3} RESULTS`;if(intros[1])intros[1].querySelector('p').textContent=`${b} QUESTIONS / ${b*3} RESULTS`;const blocks=sales$('#report').querySelectorAll('.query-number b');blocks.forEach((el,i)=>el.textContent=`${String(i+1).padStart(2,'0')} / ${n}`);sales$('#report').querySelector('.measurement-note p').textContent=`候補検索${d}問と会社名検索${b}問を3チャネルで各1回検索しました。合計${n*3}結果です。`;if(n===10){const tools=sales$('#report').querySelector('.report-tools');const print=document.createElement('button');print.className='pdf-button';print.type='button';print.textContent='PDFとして保存';print.onclick=()=>window.print();tools.prepend(print);}}
function salesEdit(){sales$('#remaining-questions').innerHTML=salesQuestions.map(q=>`<article data-id="${salesEscape(q.id)}"><label>${salesFreeIds.includes(q.id)?'無料測定済み（固定）':'完全版の質問'}<textarea ${salesFreeIds.includes(q.id)?'disabled':''}>${salesEscape(q.question_text)}</textarea></label><select ${salesFreeIds.includes(q.id)?'disabled':''}><option value="nonbrand" ${q.kind==='nonbrand'?'selected':''}>AIに候補として選ばれるか</option><option value="branded" ${q.kind==='branded'?'selected':''}>AIに自社がどう理解されているか</option></select>${salesFreeIds.includes(q.id)?'':(q.alternatives||JSON.parse(q.alternatives_json||'[]')).map(a=>`<button type="button" class="alternative">${salesEscape(a)}</button>`).join('')}</article>`).join('');document.querySelectorAll('.alternative').forEach(button=>button.onclick=()=>{button.closest('article').querySelector('textarea').value=button.textContent;});}
async function salesSave(ack=[]){const questions=[...document.querySelectorAll('#remaining-questions article')].map(el=>({id:el.dataset.id,question_text:el.querySelector('textarea').value,kind:el.querySelector('select').value}));const result=await salesApi(`${salesId}/questions`,'PUT',{questions,acknowledged_warning_codes:ack});salesWarningCodes=(result.warnings||[]).map(w=>w.code);sales$('#question-warnings').textContent=result.saved?'質問を確定しました。':[...(result.errors||[]),...(result.warnings||[])].map(w=>w.message).join('\n');sales$('#accept-warnings').hidden=result.saved||!salesWarningCodes.length;return result.saved;}
sales$('#save-questions').onclick=()=>salesSave().catch(salesError);sales$('#accept-warnings').onclick=()=>salesSave(salesWarningCodes).catch(salesError);
sales$('#checkout').onclick=async()=>{try{sales$('#checkout').disabled=true;if(salesStage==='free_completed'&&!await salesSave())return;const result=await salesApi(`${salesId}/checkout`,'POST');location.assign(result.checkoutUrl);}catch(e){salesError(e);}finally{sales$('#checkout').disabled=false;}};
async function salesPoll(){try{const data=await salesApi(salesId);salesStage=data.stage;sales$('#input-stage').hidden=true;salesQuestions=data.questions;salesFreeIds=data.free_question_ids;sales$('#progress-stage').hidden=false;const labels={questions_ready:'調査する10質問をご確認ください',free_measuring:'3質問をAIで調査しています',free_completed:'無料の9結果が揃いました',checkout_pending:'決済の確認を待っています',paid:'完全版の調査を準備しています',paid_measuring:'残り7質問をAIで調査しています',completed:'完全版の30結果が揃いました',failed:'診断処理を停止しています'};sales$('#progress-label').textContent=labels[data.stage]||data.stage;sales$('#progress-count').textContent=`${data.completed} / ${data.total} 結果`;if(data.stage==='questions_ready'){sales$('#questions-stage').hidden=false;salesShowQuestions();await salesTurnstile();return;}const report=data.full_report||data.report;if(report&&salesShown!==`${data.stage}:${report.queries.length}`){salesRenderReport(report);salesShown=`${data.stage}:${report.queries.length}`;}sales$('#upgrade').hidden=!['free_completed','checkout_pending'].includes(data.stage);sales$('#checkout').textContent=data.stage==='checkout_pending'?'決済画面をもう一度開く':'完全版を購入する · 4,980円（税込）';if(data.stage==='free_completed'){salesEdit();await salesApi(`${salesId}/event`,'POST',{event:'paid_cta_viewed'});}if(data.error)salesError(data.error);if(['free_measuring','checkout_pending','paid','paid_measuring'].includes(data.stage))setTimeout(salesPoll,5000);}catch(e){salesError(e);}}
if(salesId){if(salesToken)salesPoll();else salesError('このブラウザには診断の閲覧キーがありません。診断を開始したブラウザで開いてください。');}
else{const initialUrl=new URLSearchParams(location.search).get('url');if(initialUrl){sales$('#site-url').value=initialUrl;sales$('#site-form').requestSubmit();}}
