const e=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const tag=k=>`<span class="tag ${k}">${k==='fact'?'FACT':k==='proposal'?'提案':k==='observed'?'観測（fixture）':'仮説'}</span>`;
const a=u=>`<a href="${e(u)}" target="_blank" rel="noopener">根拠URL ↗</a>`;
function render(d){const qs=d.queries,mentions=qs.filter(x=>x.appeared).length,recs=qs.filter(x=>x.recommended).length;document.querySelector('#report').innerHTML=`
<section class="hero"><p>MADOHA PAID DIAGNOSIS / COMPLETE SAMPLE</p><h1>${e(d.subject.name)}</h1><span>${e(d.subject.area)} · ${e(d.subject.category)}</span><dl><dt>SNAPSHOT</dt><dd>${e(d.measurement.snapshotDate)}</dd><dt>RUN ID</dt><dd>${e(d.baseline.id)}</dd></dl></section>
<aside class="notice"><b>重要：実測を装わないサンプルです</b><p>${e(d.measurement.limitations)}</p></aside>
<section class="decision"><p>EXECUTIVE DECISION</p><h2>${e(d.executiveSummary.headline)}</h2><div>${tag('observed')} ${e(d.executiveSummary.currentPosition)}</div><div>${tag('proposal')} ${e(d.executiveSummary.paidValue)}</div></section>
<section><header><p>01 / CURRENT POSITION</p><h2>AI検索上の現在地</h2></header><div class="metrics"><article><span>質問への出現</span><strong>${mentions}<small> / ${qs.length}</small></strong><p>fixture</p></article><article><span>明示的な推薦</span><strong>${recs}<small> / ${qs.length}</small></strong><p>fixture</p></article><article><span>非指名での出現</span><strong>${qs.filter((x,i)=>i&&x.appeared).length}<small> / ${qs.length-1}</small></strong><p>fixture</p></article><article><span>重大な不一致候補</span><strong>${d.issues.filter(x=>x.type==='potential_misinformation').length}</strong><p>公開情報監査</p></article></div></section>
<section><header><p>02 / QUERY INTENT</p><h2>どの質問で選ばれ、どこで落ちるか</h2></header><div class="scroll"><table><thead><tr><th>質問意図・質問全文</th><th>出現</th><th>推薦</th><th>サンプル回答・根拠</th><th>主な競合</th><th>不足</th></tr></thead><tbody>${qs.map(x=>`<tr><td><em>${e(x.intent)}</em><b>${e(x.query)}</b></td><td><i class="${x.appeared?'yes':'no'}">${x.appeared?'1/1':'0/1'}</i></td><td><i class="${x.recommended?'yes':'no'}">${x.recommended?'1/1':'0/1'}</i></td><td><span class="sample-answer">fixture回答</span>${e(x.sampleAnswer)}<br>${a(x.evidenceUrl)}</td><td>${e(x.mainCompetitor)}</td><td>${e(x.gap)}</td></tr>`).join('')}</tbody></table></div></section>
<section><header><p>03 / COMPETITOR GAP</p><h2>主要競合と、強い理由</h2></header><p class="note">同じ8質問のfixture母集団による比較です。ランキング要因の断定ではありません。</p><div class="scroll comparison"><table><thead><tr><th>企業</th><th>出現</th><th>推薦</th><th>根拠URL数</th><th>強い意図</th><th>確認できた具体差</th></tr></thead><tbody>${d.comparison.map(x=>`<tr><td><b>${e(x.name)}</b></td><td>${e(x.mentions)}</td><td>${e(x.recommendations)}</td><td>${e(x.evidenceUrls)}</td><td>${e(x.winningIntent)}</td><td>${e(x.confirmedDifference)}</td></tr>`).join('')}</tbody></table></div><div class="cards">${d.competitors.map(x=>`<article>${tag('hypothesis')}<h3>${e(x.name)}</h3><b>確認できた強み</b><p>${e(x.observedStrength)}</p><b>差の仮説</b><p>${e(x.whyStronger)}</p>${a(x.source)}</article>`).join('')}</div></section>
<section><header><p>04 / SOURCES</p><h2>参照・引用され得る情報源</h2></header><div class="sources">${d.sources.map(x=>`<article><em>${e(x.type)}</em><div><h3>${e(x.name)}</h3><p>${e(x.role)}</p></div><b>${e(x.priority)}</b>${a(x.url)}</article>`).join('')}</div></section>
<section class="twocol"><div><header><p>05 / RECOGNITION</p><h2>どう認識されるか</h2></header><ul>${d.perception.recognizedAs.map(x=>`<li>${tag('observed')}${e(x)}</li>`).join('')}</ul></div><div><header><p>NOT YET CLEAR</p><h2>推薦理由として弱い情報</h2></header><ul>${d.perception.notYetClear.map(x=>`<li>${e(x)}</li>`).join('')}</ul><p class="hypo">${tag('hypothesis')}${e(d.perception.interpretation)}</p></div></section>
<section><header><p>06 / INFORMATION RISK</p><h2>誤情報・情報不足</h2></header><div class="issues">${d.issues.map(x=>`<article><span class="severity ${x.severity}">${x.severity==='high'?'優先確認':'改善候補'}</span><h3>${e(x.observed)}</h3><p><b>確認事実：</b>${e(x.fact)}</p><p><b>影響：</b>${e(x.impact)}</p><p class="fix"><b>修正：</b>${e(x.action)}</p><p><b>確認日：</b>${e(x.checkedAt)}　${a(x.evidenceUrl)}</p></article>`).join('')}</div></section>
<section><header><p>07 / PRIORITY ACTIONS</p><h2>優先順位付きの具体策</h2></header><div class="actions">${d.actions.map(x=>`<article><strong>0${x.priority}</strong><div><em>${e(x.horizon)} · ${e(x.type)}</em><h3>${e(x.target)}</h3><p>${e(x.change)}</p><dl><dt>理由</dt><dd>${e(x.reason)}</dd><dt>次回期待する変化</dt><dd>${e(x.expectedChange)}</dd><dt>検証</dt><dd>${e(x.verification)}</dd></dl></div></article>`).join('')}</div></section>
<section class="baseline"><header><p>08 / REMEASUREMENT</p><h2>次回の比較基準</h2></header><div class="metrics">${d.baseline.metrics.map(x=>`<article><span>${e(x.name)}</span><strong>${e(x.value)}</strong><p>${e(x.definition)}</p></article>`).join('')}</div><p>${e(d.baseline.remeasurement)}</p><div class="measure-plan"><article><h3>固定する条件</h3><ul>${d.baseline.fixedConditions.map(x=>`<li>${e(x)}</li>`).join('')}</ul></article><article><h3>次回目標</h3><ul>${d.baseline.targets.map(x=>`<li>${e(x)}</li>`).join('')}</ul></article></div><footer>モデル：${e(d.measurement.models.join(', '))} ／ 質問：${d.measurement.queryCount}件 ／ サンプル反復：${d.measurement.repetitions}回 ／ 本番予定：各3回 ／ ${e(d.measurement.snapshotDate)}</footer></section>
<section><header><p>FACT LEDGER</p><h2>確認事実と根拠</h2></header><div class="facts">${d.facts.map(x=>`<article>${tag('fact')}<p>${e(x.claim)}</p><span>${e(x.evidence)}</span>${a(x.source)}</article>`).join('')}</div></section>
<footer class="end"><b>MADOHA</b><p>本番診断ではAI回答、引用URL、測定条件を注文ごとに保存します。</p><a href="index.html">無料チェックへ戻る</a></footer>`}
if (globalThis.MADOHA_KYOUDO_SAMPLE) render(globalThis.MADOHA_KYOUDO_SAMPLE);
else fetch('./data/samples/kyoudo-housing-paid-diagnosis.json').then(r=>r.ok?r.json():Promise.reject()).then(render).catch(()=>document.querySelector('#report').innerHTML='<p class="loading">サンプルを読み込めませんでした。</p>');
