const e=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char]);
const definitions={fact:'公式サイトや公開情報で確認できた事実',observed:'今回の検索テストで確認した結果（サンプルでは仮データ）',hypothesis:'観測から考えられる原因。確定事項ではありません',proposal:'MADOHAが推奨する改善策'};
const tag=kind=>`<span class="tag ${kind}" title="${e(definitions[kind])}">${kind==='fact'?'FACT':kind==='observed'?'観測':kind==='hypothesis'?'仮説':'提案'}</span>`;
const link=url=>`<a href="${e(url)}" target="_blank" rel="noopener">根拠ページ ↗</a>`;
const importance=(label,kind)=>`<span class="importance ${kind}">${e(label)}</span>`;
const actionLabel=priority=>priority===1?importance('最優先','critical'):importance('重要','important');
const actionType=type=>({'FACT FIX':'事実情報の修正','EVIDENCE':'根拠情報の強化','ANSWER CONTENT':'質問に答えるページの整備','LOCAL AUTHORITY':'地域情報の強化','THIRD-PARTY':'第三者情報の強化'}[type]||type);

function render(data){
  const queries=data.queries,mentions=queries.filter(x=>x.appeared).length,recommendations=queries.filter(x=>x.recommended).length;
  const nonBrandMentions=queries.slice(1).filter(x=>x.appeared).length,topActions=data.actions.slice(0,3);
  const missed=queries.filter(x=>!x.recommended&&x.intent!=='指名確認').map(x=>x.intent).join('、');
  document.querySelector('#report').innerHTML=`
  <section class="hero compact-hero"><p>MADOHA 有料詳細診断 / 完成版サンプル</p><h1>${e(data.subject.name)}</h1><span>${e(data.subject.area)} · ${e(data.subject.category)}</span><dl><dt>基準日</dt><dd>${e(data.measurement.snapshotDate)}</dd><dt>診断ID</dt><dd>${e(data.baseline.id)}</dd></dl></section>

  <section class="executive-summary"><div class="summary-heading"><div><p>30秒で分かる診断結果</p><h2>経営判断サマリー</h2></div><div class="rating"><span>総合評価（仮判定）</span><strong>${e(data.executiveSummary.overallRating)}</strong><small>改善余地：${e(data.executiveSummary.improvementPotential)}</small></div></div><h3>${e(data.executiveSummary.headline)}</h3><div class="summary-grid"><article class="summary-loss">${importance('最優先','critical')}<h4>最大の機会損失</h4><p>${e(data.executiveSummary.opportunityLoss)}</p></article><article>${importance('重要','important')}<h4>競合との差</h4><p>${e(data.executiveSummary.competitorGap)}</p></article><article>${importance('重要','important')}<h4>今回の重要ポイント</h4><p>${e(data.executiveSummary.keyPoint)}</p></article></div><div class="top-actions"><h4>まず実行する3件</h4>${topActions.map(x=>`<article>${actionLabel(x.priority)}<strong>${x.priority}</strong><div><small>${e(x.horizon)}以内</small><p>${e(x.target)}</p></div></article>`).join('')}</div><p class="sample-caution"><b>商品確認用サンプル：</b>出現・推薦の数値と総合評価は仮データです。本番の実測結果ではありません。</p></section>

  <section class="evidence-legend"><h2>表示ラベルの意味</h2><div>${Object.keys(definitions).map(kind=>`<p>${tag(kind)}${e(definitions[kind])}</p>`).join('')}</div></section>

  <section><header><p>01 / 重要な根拠</p><h2>現在の状態と、その意味</h2></header><p class="section-lead">商品確認用の8質問では、4問で社名が出ました。推薦されたのは2問です。</p><div class="metrics"><article><span>回答に社名が出た</span><strong>${mentions}<small> / ${queries.length}</small></strong><p>AI検索での表示状況</p></article><article><span>相談先として推薦された</span><strong>${recommendations}<small> / ${queries.length}</small></strong><p>AI検索での推薦状況</p></article><article><span>会社名なしで社名が出た</span><strong>${nonBrandMentions}<small> / ${queries.length-1}</small></strong><p>一般的な質問での表示</p></article><article><span>表現の確認が必要</span><strong>${data.issues.filter(x=>x.type==='potential_misinformation').length}</strong><p>公開情報の監査結果</p></article></div><div class="key-evidence"><article>${importance('問題なし','ok')}${tag('observed')}<h3>複合相談は強みです</h3><p>指名質問と「購入＋リフォーム」では推薦候補になりました。</p><b>意味</b><p>複数の相談を一社で扱える点は、選ばれる理由にできます。</p></article><article>${importance('重要','important')}${tag('observed')}<h3>対応可能だけでは選ばれません</h3><p>${e(missed)}では推薦されませんでした。</p><b>意味</b><p>実績や事例がないと、他社より優先する理由を説明できません。</p></article><article>${importance('最優先','critical')}${tag('fact')}<h3>営業年数は確認が必要です</h3><p>公式サイトに営業年数の表現があります。免許取得日は創立日を証明しません。</p><b>意味</b><p>年数の基準を統一しないと、異なる情報が回答される恐れがあります。</p></article></div></section>

  <section><header><p>02 / 最優先施策</p><h2>まず、この3件から着手してください</h2></header><div class="actions priority-actions">${topActions.map(x=>`<article>${actionLabel(x.priority)}<strong>0${x.priority}</strong><div><em>${e(x.horizon)}以内 · ${e(actionType(x.type))}</em><h3>${e(x.target)}</h3><p>${e(x.change)}</p><dl><dt>なぜ必要か</dt><dd>${e(x.reason)}</dd><dt>次回確認すること</dt><dd>${e(x.verification)}</dd></dl></div></article>`).join('')}</div></section>

  <section class="twocol"><div><header><p>03 / 会社の見え方</p><h2>公開情報から読み取れる会社像</h2></header><p class="meaning-note">公開情報をもとに、どのような会社として説明できるかを示します。</p><ul>${data.perception.recognizedAs.map(x=>`<li>${importance('問題なし','ok')}${tag('observed')}${e(x)}</li>`).join('')}</ul></div><div><header><p>まだ弱い情報</p><h2>選ばれる理由として不足</h2></header><p class="meaning-note">対応できることと、選ぶべき理由は別です。</p><ul>${data.perception.notYetClear.map(x=>`<li>${importance('重要','important')}${e(x)}</li>`).join('')}</ul><p class="hypo">${tag('hypothesis')}${e(data.perception.interpretation)}</p></div></section>

  <section><header><p>04 / 誤情報・情報不足</p><h2>放置すると不利益につながる項目</h2></header><div class="issues">${data.issues.map(x=>`<article>${importance(x.severity==='high'?'最優先':'重要',x.severity==='high'?'critical':'important')}<h3>${e(x.observed)}</h3><p>${tag('fact')}<b>確認できた事実</b><br>${e(x.fact)}</p><p>${tag('observed')}<b>今回確認したこと</b><br>${e(x.observed)}</p><p>${tag('hypothesis')}<b>考えられる影響</b><br>${e(x.impact)}</p><p class="fix">${tag('proposal')}<b>何をするか</b><br>${e(x.action)}</p><p><b>確認日：</b>${e(x.checkedAt)}　${link(x.evidenceUrl)}</p></article>`).join('')}</div></section>

  <section class="detail-break"><p>ここからは判断の根拠です</p><h2>必要な箇所だけ詳しく確認できます</h2><p>前半の結論を、質問別の結果・競合・情報源・確認事実で確かめられます。</p></section>

  <section><header><p>05 / 質問ごとの結果</p><h2>どの質問で選ばれ、どこで選ばれないか</h2></header><p class="meaning-note"><b>質問の目的</b>とは、利用者がAIに尋ねる場面です。表示は「回答に社名が出た」、推薦は「相談先として挙げられた」を意味します。</p><div class="scroll"><table><thead><tr><th>質問の目的・全文</th><th>表示（仮データ）</th><th>推薦（仮データ）</th><th>商品確認用の回答例・根拠</th><th>主な競合</th><th>不足情報</th></tr></thead><tbody>${queries.map(x=>`<tr><td><em>${e(x.intent)}</em><b>${e(x.query)}</b></td><td><i class="${x.appeared?'yes':'no'}">${x.appeared?'あり':'なし'}</i></td><td><i class="${x.recommended?'yes':'no'}">${x.recommended?'あり':'なし'}</i></td><td><span class="sample-answer">仮データの回答</span>${e(x.sampleAnswer)}<br>${link(x.evidenceUrl)}</td><td>${e(x.mainCompetitor)}</td><td>${e(x.gap)}</td></tr>`).join('')}</tbody></table></div></section>

  <section><header><p>06 / 競合との比較</p><h2>競合が表示・推薦されやすい理由</h2></header><p class="meaning-note">同じ8質問の仮データによる比較です。AIの仕組みを断定するものではありません。</p><div class="scroll comparison"><table><thead><tr><th>企業</th><th>表示（仮データ）</th><th>推薦（仮データ）</th><th>根拠ページ数</th><th>強い質問（仮データ）</th><th>公開情報で確認できた違い</th></tr></thead><tbody>${data.comparison.map(x=>`<tr><td><b>${e(x.name)}</b></td><td>${e(x.mentions)}</td><td>${e(x.recommendations)}</td><td>${e(x.evidenceUrls)}</td><td>${e(x.winningIntent)}</td><td>${e(x.confirmedDifference)}</td></tr>`).join('')}</tbody></table></div><div class="cards">${data.competitors.map(x=>`<article>${importance('要確認','check')}<h3>${e(x.name)}</h3><p>${tag('fact')}<b>公開情報で確認した強み</b><br>${e(x.observedStrength)}</p><p>${tag('hypothesis')}<b>強い理由の仮説</b><br>${e(x.whyStronger)}</p>${link(x.source)}</article>`).join('')}</div></section>

  <section><header><p>07 / 参考情報源</p><h2>AIが回答の参考にする可能性があるWebページ</h2></header><div class="sources">${data.sources.map(x=>`<article><em>${e(x.type)}</em><div><h3>${e(x.name)}</h3><p>${e(x.role)}</p></div><b>${e(x.priority)}</b>${link(x.url)}</article>`).join('')}</div></section>

  <section><header><p>08 / 確認事実</p><h2>FACTと根拠ページ</h2></header><p class="meaning-note">提案や推測ではありません。公開情報で確認できた事実だけをまとめています。</p><div class="facts">${data.facts.map(x=>`<article>${importance('問題なし','ok')}${tag('fact')}<p>${e(x.claim)}</p><span>${e(x.evidence)}</span>${link(x.source)}</article>`).join('')}</div></section>

  <section><header><p>09 / 具体策の全体像</p><h2>優先順位付きの具体策5件</h2></header><div class="actions">${data.actions.map(x=>`<article>${actionLabel(x.priority)}<strong>0${x.priority}</strong><div><em>${e(x.horizon)}以内 · ${e(actionType(x.type))}</em><h3>${e(x.target)}</h3><p>${e(x.change)}</p><dl><dt>なぜ必要か</dt><dd>${e(x.reason)}</dd><dt>期待する変化</dt><dd>${e(x.expectedChange)}</dd><dt>次回確認すること</dt><dd>${e(x.verification)}</dd></dl></div></article>`).join('')}</div></section>

  <section class="baseline"><header><p>10 / 次回測定</p><h2>改善前後を比べる基準</h2></header><p>${e(data.baseline.remeasurement)}</p><div class="metrics">${data.baseline.metrics.map(x=>`<article><span>${e(x.name)}</span><strong>${e(x.value)}</strong><p>${e(x.definition)}</p></article>`).join('')}</div><div class="measure-plan"><article><h3>同じ条件で比べる項目</h3><ul>${data.baseline.fixedConditions.map(x=>`<li>${e(x)}</li>`).join('')}</ul></article><article><h3>次回の目標</h3><ul>${data.baseline.targets.map(x=>`<li>${e(x)}</li>`).join('')}</ul></article></div><footer>使用データ：${e(data.measurement.models.join(', '))} ／ 質問：${data.measurement.queryCount}件 ／ サンプル反復：${data.measurement.repetitions}回 ／ 本番予定：各3回 ／ ${e(data.measurement.snapshotDate)}</footer></section>
  <aside class="notice"><b>サンプルについて</b><p>${e(data.measurement.limitations)}</p></aside><footer class="end"><b>MADOHA</b><p>何が起きているか、なぜ問題か、何をするかを一つの診断にまとめます。</p><a href="index.html">無料チェックへ戻る</a></footer>`;
}
if(globalThis.MADOHA_KYOUDO_SAMPLE)render(globalThis.MADOHA_KYOUDO_SAMPLE);else fetch('./data/samples/kyoudo-housing-paid-diagnosis.json').then(r=>r.ok?r.json():Promise.reject()).then(render).catch(()=>document.querySelector('#report').innerHTML='<p class="loading">サンプルを読み込めませんでした。</p>');
