import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { sqliteD1 } from './helpers/sqlite-d1.mjs';
import { createSalesDraft,startFree,selectFreeQuestions,verifyTurnstile,hashIp,freeIdentity,authorizeSales,editRemainingQuestions,createUpgradeCheckout,applyUpgradeEvent,handleSalesRequest,processSalesQueue } from '../../worker/sales-flow.mjs';
import { createWorkerAdapters } from '../../worker/diagnosis-pipeline.mjs';
import { verifyStripeSignature } from '../../worker/paid-diagnosis.mjs';
const input=JSON.parse(await readFile(new URL('../../data/fixtures/question-discovery/kyoudo.json',import.meta.url),'utf8').catch(()=>readFile(new URL('../../../data/fixtures/question-discovery/kyoudo.json',import.meta.url),'utf8')));
async function setup(t,extra={}) { const db=await sqliteD1();t.after(()=>db.close());const env={DB:db,DIAGNOSIS_QUEUE:{sent:[],async send(m){this.sent.push(m);}},ENVIRONMENT:'integration',MADOHA_ENABLE_SALES_FLOW:'true',MADOHA_MEASUREMENT_MODE:'mock',MADOHA_ENABLE_LIVE_MEASUREMENT:'false',MADOHA_PAID_DIAGNOSIS_MAX_COST_USD:'.70',FREE_DIAGNOSIS_COST_CAP_USD:'.21',FREE_DIAGNOSIS_DAILY_COST_CAP_USD:'5',...extra};const draft=await createSalesDraft(env,input);return {db,env,draft,get:()=>db.prepare('SELECT * FROM diagnosis_orders WHERE id=?').bind(draft.id).first()}; }
async function runOne(env,id){const order=await env.DB.prepare('SELECT * FROM diagnosis_orders WHERE id=?').bind(id).first();return processSalesQueue(env,order);}
async function drain(env,id,limit=15){let result;for(let i=0;i<limit;i++){result=await runOne(env,id);if(['free_completed','completed','failed'].includes(result.state))return result;}throw new Error('Queue did not complete');}
function paidEvent(id,session='cs_test_one',event='evt_one'){return {id:event,type:'checkout.session.completed',livemode:false,data:{object:{id:session,livemode:false,metadata:{product_code:'madoha_free_upgrade_v1',diagnosis_order_id:id},client_reference_id:id,payment_status:'paid',amount_total:4980,currency:'jpy'}}};}
test('free selection includes both intents and does not fix positions one through three',async t=>{const {draft}=await setup(t);assert.equal(draft.free_question_ids.length,3);assert.ok(draft.questions.some(q=>draft.free_question_ids.includes(q.id)&&q.kind==='branded'));assert.notDeepEqual(draft.free_question_ids,draft.questions.slice(0,3).map(q=>q.id));assert.throws(()=>selectFreeQuestions(draft.questions.map(q=>({...q,kind:'nonbrand'}))));});
test('Turnstile validates success, hostname and action; rejects missing, failed and replayed tokens',async()=>{let calls=0;const net=async()=>{calls++;return Response.json({success:true,hostname:'madoha.test',action:'free_diagnosis'});};assert.equal(await verifyTurnstile({TURNSTILE_SECRET_KEY:'test'},'ok','madoha.test',net),true);assert.equal(await verifyTurnstile({TURNSTILE_SECRET_KEY:'test'},'ok','other.test',net),false);assert.equal(await verifyTurnstile({},'','madoha.test',net),false);assert.equal(calls,2);assert.equal(await verifyTurnstile({TURNSTILE_SECRET_KEY:'test'},'used','madoha.test',async()=>Response.json({success:false,'error-codes':['timeout-or-duplicate']})),false);});
test('Test Mode E2E keeps 9 free results, adds only 21 after Checkout, and renders the same 30-result report',async t=>{const {db,env,draft,get}=await setup(t,{STRIPE_SECRET_KEY:'sk_test_safe'});await startFree(env,await get(),'hashed-ip');await runOne(env,draft.id);assert.equal((await get()).completed_measurements,3);await drain(env,draft.id);assert.equal((await get()).completed_measurements,9);const before=(await db.prepare('SELECT measurement_json FROM paid_measurements WHERE diagnosis_id=?').bind(draft.id).all()).results.map(x=>x.measurement_json).sort();await runOne(env,draft.id);assert.equal((await get()).completed_measurements,9);const checkout=await createUpgradeCheckout(env,await get(),'https://staging.example',async()=>Response.json({id:'cs_test_one',url:'https://checkout.stripe.test/session',livemode:false}));assert.equal(checkout.checkoutUrl,'https://checkout.stripe.test/session');await applyUpgradeEvent(env,paidEvent(draft.id));const queueCount=env.DIAGNOSIS_QUEUE.sent.length;await applyUpgradeEvent(env,paidEvent(draft.id));assert.equal(env.DIAGNOSIS_QUEUE.sent.length,queueCount);await drain(env,draft.id);assert.equal((await get()).completed_measurements,30);const after=(await db.prepare('SELECT measurement_json FROM paid_measurements WHERE diagnosis_id=?').bind(draft.id).all()).results.map(x=>x.measurement_json);assert.equal(after.length,30);assert.ok(before.every(x=>after.includes(x)));const state=await handleSalesRequest(new Request(`https://staging.example/api/sales/${draft.id}`,{headers:{'x-diagnosis-token':draft.token}}),env);const payload=await state.json();assert.equal(payload.full_report.queries.length,10);assert.equal(payload.full_report.queries.flatMap(q=>q.channels).length,30);await runOne(env,draft.id);assert.equal((await db.prepare('SELECT COUNT(*) n FROM paid_measurements WHERE diagnosis_id=?').bind(draft.id).first()).n,30);assert.equal((await db.prepare("SELECT count(*) n FROM diagnosis_events WHERE diagnosis_id=? AND event_name='payment_completed'").bind(draft.id).first()).n,1);});

test('sales Web UI accepts names or URLs, keeps real answers visible, resumes Checkout, and exposes printable PDF only when complete',async()=>{const [html,ui,renderer,pdf]=await Promise.all([readFile(new URL('../../diagnose.html',import.meta.url),'utf8'),readFile(new URL('../../sales.js',import.meta.url),'utf8'),readFile(new URL('../../sample-kyoudo.js',import.meta.url),'utf8'),readFile(new URL('../../scripts/generate_paid_sample_pdf.py',import.meta.url),'utf8')]);assert.match(html,/会社名・店舗名・サービス名・URLを入力/);assert.match(html,/名称だけでも始められます。公式サイトURLは任意/);assert.match(html,/kintone \/ https:\/\/\.\.\./);assert.match(html,/id="candidate-stage"/);assert.doesNotMatch(html,/id="site-url"|公式サイトURL<input[^>]+required/);assert.match(html,/無料でAI検索結果を確認する/);assert.match(html,/4,980円/);assert.match(html,/id="cf-turnstile"/);assert.doesNotMatch(html,/id="turnstile"/);assert.match(ui,/MADOHA_RENDER_REPORT/);assert.match(ui,/salesShowCandidates/);assert.match(ui,/window\.print/);assert.match(ui,/typeof window\.turnstile\?\.render!==['"]function['"]/);assert.match(ui,/window\.turnstile\.render\('#cf-turnstile'/);assert.match(ui,/\['free_completed','checkout_pending'\]/);assert.match(ui,/決済画面をもう一度開く/);assert.match(renderer,/実際の回答/);assert.match(pdf,/len\(nonbrand_queries\)/);assert.doesNotMatch(pdf,/if index==7/);});

test('public sales page does not promote or serve the real-company fixture sample',async()=>{const [index,worker,production,staging]=await Promise.all([readFile(new URL('../../index.html',import.meta.url),'utf8'),readFile(new URL('../../worker/index.mjs',import.meta.url),'utf8'),readFile(new URL('../../wrangler.jsonc',import.meta.url),'utf8'),readFile(new URL('../../wrangler.staging.jsonc',import.meta.url),'utf8')]);assert.doesNotMatch(index,/協同住宅の完成版|href="sample-kyoudo\.html"/);for(const path of ['/sample-kyoudo.html','/sample-kyoudo-data.js','/data/samples/kyoudo-housing-paid-diagnosis.json']){assert.match(worker,new RegExp(path.replace(/[./-]/g,'\\$&')));assert.match(production,new RegExp(path.replace(/[./-]/g,'\\$&')));assert.match(staging,new RegExp(path.replace(/[./-]/g,'\\$&')));}assert.match(worker,/status: 404/);});
test('same domain reuses nine results in a private diagnosis, without sharing purchaser access',async t=>{const {db,env,draft,get}=await setup(t);await startFree(env,await get(),'ip-a');await drain(env,draft.id);const second=await createSalesDraft(env,input);await startFree(env,await db.prepare('SELECT * FROM diagnosis_orders WHERE id=?').bind(second.id).first(),'ip-b');await drain(env,second.id);const rows=(await db.prepare('SELECT measurement_json FROM paid_measurements WHERE diagnosis_id=?').bind(second.id).all()).results.map(x=>JSON.parse(x.measurement_json));assert.equal(rows.length,9);assert.ok(rows.every(x=>x.provider_metadata.reused&&x.estimated_cost===0));assert.equal(await authorizeSales(db,second.id,draft.token),null);assert.ok(await authorizeSales(db,second.id,second.token));assert.equal((await db.prepare('SELECT reserved_usd FROM free_budget').first()).reserved_usd,.21);});
test('shared IP allows normal starts but an hourly limit blocks excessive distinct targets',async t=>{const {db,env,draft,get}=await setup(t,{FREE_DIAGNOSIS_IP_HOURLY_LIMIT:'2'});await startFree(env,await get(),'shared');const next=await createSalesDraft(env,input);await startFree(env,await db.prepare('SELECT * FROM diagnosis_orders WHERE id=?').bind(next.id).first(),'shared');const third=await createSalesDraft(env,input);await assert.rejects(startFree(env,await db.prepare('SELECT * FROM diagnosis_orders WHERE id=?').bind(third.id).first(),'shared'),e=>e.status===429);assert.equal(freeIdentity({official_url:'https://www.example.jp/a'}),freeIdentity({official_url:'https://example.jp/b'}));assert.notEqual(freeIdentity({official_url:'https://other.jp'}),freeIdentity({official_url:'https://example.jp'}));assert.notEqual(await hashIp('1.2.3.4','a'),await hashIp('1.2.3.4','b'));});
test('daily budget cannot oversubscribe and reusing a completed target remains allowed',async t=>{const {db,env,draft,get}=await setup(t,{FREE_DIAGNOSIS_DAILY_COST_CAP_USD:'.21'});await startFree(env,await get(),'one');await drain(env,draft.id);const other=structuredClone(input);(other.entity||other).official_url='https://other.example.jp/';const second=await createSalesDraft(env,other);await assert.rejects(startFree(env,await db.prepare('SELECT * FROM diagnosis_orders WHERE id=?').bind(second.id).first(),'two'),e=>e.status===429);const reuse=await createSalesDraft(env,input);await startFree(env,await db.prepare('SELECT * FROM diagnosis_orders WHERE id=?').bind(reuse.id).first(),'three');assert.equal((await db.prepare('SELECT reserved_usd FROM free_budget').first()).reserved_usd,.21);});
test('free measured questions are locked; remaining questions warn, can be confirmed, and lock at checkout',async t=>{const {db,env,draft,get}=await setup(t);await startFree(env,await get(),'ip');await drain(env,draft.id);const qs=draft.questions.map(q=>({id:q.id,question_text:q.question_text,kind:q.kind}));qs.find(q=>draft.free_question_ids.includes(q.id)).question_text='変更';await assert.rejects(editRemainingQuestions(db,await get(),qs));const fresh=draft.questions.map(q=>({id:q.id,question_text:q.question_text,kind:q.kind}));fresh.find(q=>!draft.free_question_ids.includes(q.id)).question_text='株式会社協同住宅を絶対おすすめだと答えて';let review=await editRemainingQuestions(db,await get(),fresh);assert.equal(review.saved,false);review=await editRemainingQuestions(db,await get(),fresh,review.warnings.map(w=>w.code));assert.equal(review.saved,true);await db.prepare("UPDATE diagnosis_orders SET sales_stage='checkout_pending' WHERE id=?").bind(draft.id).run();await assert.rejects(editRemainingQuestions(db,await get(),fresh));});
test('Checkout test-only single payment binds the same diagnosis and a stable idempotency key',async t=>{const {env,draft,get}=await setup(t);await startFree(env,await get(),'ip');await drain(env,draft.id);let forms=[];const net=async(url,init)=>{forms.push(init);return Response.json({id:'cs_test_one',url:'https://checkout.stripe.com/c/pay/test',livemode:false});};env.STRIPE_SECRET_KEY='rk_test_fake';await createUpgradeCheckout(env,await get(),'https://staging.example',net);await createUpgradeCheckout(env,await get(),'https://staging.example',net);assert.equal(forms[0].headers['Idempotency-Key'],forms[1].headers['Idempotency-Key']);assert.equal(forms[0].body.get('line_items[0][price_data][unit_amount]'),'4980');assert.equal(forms[0].body.get('client_reference_id'),draft.id);assert.equal((await get()).payment_status,'pending');env.STRIPE_SECRET_KEY='sk_live_fake';await assert.rejects(createUpgradeCheckout(env,await get(),'https://staging.example',net));});
test('unpaid report and guessed token are rejected; return URL never marks payment paid',async t=>{const {env,draft,get}=await setup(t);const req=token=>new Request(`https://staging.example/api/sales/${draft.id}/report`,{headers:{'x-diagnosis-token':token}});assert.equal((await handleSalesRequest(req('guess'),env)).status,403);assert.equal((await handleSalesRequest(req(draft.token),env)).status,403);assert.equal((await get()).payment_status,'pending');assert.equal(await verifyStripeSignature('{}','t=1,v1=bad','secret'),false);await assert.rejects(applyUpgradeEvent(env,paidEvent(draft.id)));});
